    CREATE TABLE users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    age INT (3) NOT NULL,
    birthday DATE NOT NULL,
    address VARCHAR(150) NOT NULL); 
